name: V 0.4.0 ðŸ tests

on:
  push:
    branches: [ "kirill/tests-temp-exp" ]
  pull_request:
    branches: ["kirill/tests-temp-exp"]
    paths:
      - ".github/workflows/pytests-chain.yaml"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      # https://www.notion.so/nibiru/Resources-and-Repo-Configs-b31aa8074a2b419d80b0c946ed5efab0
      CHAIN_ID: ${{ secrets.CHAIN_ID }}
      HOST: localhost
      VALIDATOR_MNEMONIC: ${{ secrets.VALIDATOR_MNEMONIC }}
      ORACLE_MNEMONIC: ${{ secrets.ORACLE_MNEMONIC }}
      GRPC_PORT: ${{ secrets.GRPC_PORT }}
      LCD_PORT: ${{ secrets.LCD_PORT }}
      NETWORK_INSECURE: ${{ secrets.NETWORK_INSECURE }}
      WEBSOCKET_ENDPOINT: ${{ secrets.WEBSOCKET_ENDPOINT }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: 'HEAD~'
      - name: Show Tag
        run: |
          echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'
          echo ${{ steps.get_version.outputs.version }}
          echo ${{ steps.get_version.outputs.version-without-v }}

      - name: Read Toml
        uses: SebRollen/toml-action@v1.0.0
        id: read_toml
        with:
          file: 'pyproject.toml'
          field: 'name'
      - name: Show Toml
        run: |
         echo 'Output Toml Value: ${{steps.read_toml.outputs.content}}'
          

  # write something in a file and create it
      - run: echo "value" >> new.txt

  # read from file and assign to outputs object
      - name: Read and assign
        id: output_test
        run: |
          input_file="pyproject.toml"
          current_version="1"
          while read line
          do
           file_text=$line     
            if [[ "$line" == "version ="* ]]; then
            echo ::set-output name=new_value::$line
           fi
           done < "$input_file"
          

  # test to see if done correctly - should echo "value"
      - run: echo ${{steps.output_test.outputs.new_value }}

  # test to see if done correctly - should echo "value"
      - run: echo ${{steps.output_test.outputs.new_value }}

      # ----------------------------------------------
      # check-out nibiru V0.4.0 repo and deploy
      # ----------------------------------------------
      - name: Checkout nibiru V0.4.0
        if: (steps.output_test.outputs.new_value == 'version = "0.4.0"')
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.NIBIBOT_GIT_TOKEN }}
          repository: NibiruChain/nibiru
          ref: refs/tags/v0.14.0

      - name: Set up Go
        if: (steps.output_test.outputs.new_value == 'version = "0.4.0"')
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
#
      - name: Run make build
        if: (steps.output_test.outputs.new_value == 'version = "0.4.0"')
        run: |
          make build
          make install
#
      - name: Run make localnet
        if: (steps.output_test.outputs.new_value == 'version = "0.4.0"')
        run: |
          make localnet &

      # ----------------------------------------------
      # check-out repo and set-up python
      # ----------------------------------------------
      - name: Check out the repo
        if: (steps.output_test.outputs.new_value == 'version = "0.4.0"')
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        if: (steps.output_test.outputs.new_value == 'version = "0.4.0"')
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.13

      - name: Run python
        if: (steps.output_test.outputs.new_value == 'version = "0.4.0"')
        run: python --version && python -c "print('hello')"



      # ----------------------------------------------
      # Try to load a cached poetry binary
      # See https://github.com/snok/install-poetry#caching-the-poetry-installation for the source
      # ----------------------------------------------
      - name: Load cached Poetry installation
        if: (steps.output_test.outputs.new_value == 'version = "0.4.0"')
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-0 # increment to reset cache
      # ----------------------------------------------
      # Install & configure poetry
      # ----------------------------------------------
      - name: Install Poetry
        if: (steps.output_test.outputs.new_value == 'version = "0.4.0"')
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      # load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        if: (steps.output_test.outputs.new_value == 'version = "0.4.0"')
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        if: (steps.output_test.outputs.new_value == 'version = "0.4.0"')
        run: poetry install --no-interaction --no-root

      - run: sleep 10s
      #----------------------------------------------
      # run tests
      #----------------------------------------------
      - name: Run Python SDK tests
        if: (steps.output_test.outputs.new_value == 'version = "0.4.0"')
        run: poetry run pytest -s --html=report.html --junitxml=./reports/report-xml.xml


        #----------------------------------------------
        # publish report xml
        #----------------------------------------------

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/report-xml.xml    # Path to test results
          reporter: jest-junit
